
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BASE
{

using System;
    using System.Collections.Generic;
    
public partial class tContactCommittee
{

    public int ContactCommitteeID { get; set; }

    public int ContactID { get; set; }

    public int CommitteeID { get; set; }

    public Nullable<bool> Disabled { get; set; }



    public virtual tCommittee tCommittee { get; set; }

    public virtual tContact tContact { get; set; }

}

}
