
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BASE
{

using System;
    using System.Collections.Generic;
    
public partial class tContact
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tContact()
    {

        this.tContactCommittee = new HashSet<tContactCommittee>();

    }


    public int ContactID { get; set; }

    public int GranteeID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PrimaryPhone { get; set; }

    public string SecondaryPhone { get; set; }

    public string PrimaryEmail { get; set; }

    public string MemberNumber { get; set; }

    public Nullable<bool> RegionHSParticipation { get; set; }

    public Nullable<bool> NationalHSParticipation { get; set; }

    public Nullable<bool> Disabled { get; set; }



    public virtual tGrantee tGrantee { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tContactCommittee> tContactCommittee { get; set; }

}

}
