
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BASE
{

using System;
    using System.Collections.Generic;
    
public partial class tGrantee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tGrantee()
    {

        this.tContact = new HashSet<tContact>();

    }


    public int GranteeID { get; set; }

    public string GranteeName { get; set; }

    public string GranteeAddress1 { get; set; }

    public string GranteeAddress2 { get; set; }

    public string GranteeCity { get; set; }

    public string GranteeState { get; set; }

    public string GranteeZip { get; set; }

    public Nullable<bool> Disabled { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tContact> tContact { get; set; }

}

}
