//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPersonRole
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int RoleID { get; set; }
    
        public virtual tPerson tPerson { get; set; }
        public virtual tRole tRole { get; set; }
    }
}
