//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPrice
    {
        public int ID { get; set; }
        public int PriceTypeID { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
    
        public virtual tPriceType tPriceType { get; set; }
    }
}
